# -*- coding: utf-8 -*-
"""Untitled1.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1I8RTld3s6lhAKDcDdmN6h-yD7n0MmVxf
"""

class Contact:
    def __init__(self, name, phone):
        self.name = name
        self.phone = phone

class ContactManager:
    def __init__(self):
        self.contacts = []

    def add_contact(self, name, phone):
        new_contact = Contact(name, phone)
        self.contacts.append(new_contact)
        print(f"Added contact: {name}, {phone}")

    def remove_contact(self, name):
        for contact in self.contacts:
            if contact.name == name:
                self.contacts.remove(contact)
                print(f"Removed contact: {name}")
                return
        print(f"Contact not found: {name}")

    def search_contact(self, name):
        for contact in self.contacts:
            if contact.name == name:
                print(f"Found contact: {name}, {contact.phone}")
                return
        print(f"Contact not found: {name}")

    def display_contacts(self):
        if not self.contacts:
            print("No contacts available.")
        else:
            for contact in self.contacts:
                print(f"Name: {contact.name}, Phone: {contact.phone}")

def main():
    manager = ContactManager()

    while True:
        print("\n1. Add Contact")
        print("\n2. Remove Contact")
        print("\n3. Search Contact")
        print("\n4. Display All Contacts")
        print("\n5. Exit")

        choice = input("\nEnter your choice: ")

        if choice == '1':
            name = input("Enter name: ")
            phone = input("Enter phone number: ")
            manager.add_contact(name, phone)
        elif choice == '2':
            name = input("Enter name to remove: ")
            manager.remove_contact(name)
        elif choice == '3':
            name = input("Enter name to search: ")
            manager.search_contact(name)
        elif choice == '4':
            manager.display_contacts()
        elif choice == '5':
            break
        else:
            print("Invalid choice. Please try again.")

if __name__ == "__main__":
    main()